name: "Build & test static embeds (nix)"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.iog.io
    - uses: cachix/cachix-action@v14
      with:
        name: luispedro
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build -f build-scripts/ngless-static-embed-dependencies.nix projectCross.musl64.hsPkgs.NGLess.components.exes.ngless --out-link ngless-static-embed
    - run: nix-shell build-scripts/shell-static.nix --pure --command ./run-tests.sh

    - run: nix build -f release.nix projectCross.musl64.hsPkgs.NGLess.components.exes.ngless --out-link ngless-static

    - name: "Upload with embeds"
      uses: actions/upload-artifact@v4
      with:
        name: ngless_static-embed
        path: ngless-static-embed/bin/ngless


    - name: "Upload without embeds"
      uses: actions/upload-artifact@v4
      with:
        name: ngless_static
        path: ngless-static/bin/ngless

